### ISSUE TITLE
Breaking chairs results in floating player

### ISSUE THREAD

**Issue by ChiboYen** [illa4257/OpenSit#1]
When a player breaks the stair that they're sitting on, it doesn't kick them from their seat (but it should, the chair/stair is gone).

**Comment by illa4257** [comment]
Thank you for report!

**Comment by ChiboYen** [comment]
Thank you for the bug fix! Will there be a release on modrinth or github? I appreciate it!

**Comment by illa4257** [comment]
> Thank you for the bug fix! Will there be a release on modrinth or github? I appreciate it!

Yes, but later
